server:
  port: 8080

spring:
  profiles:
    active: db
  config:
    import: "optional:file:.env[.properties]" # references the .env file in the root directory for environment variables
  datasource:
    url: jdbc:postgresql://${PG_HOST}/${PG_DATABASE}?sslmode=require # neon free tier database https://console.neon.tech/
    driver-class-name: org.postgresql.Driver
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate # validates schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    baseline-on-migrate: true
#    baseline-description: "init"
#    baseline-version: 0
#    enabled: true
#    user: ${PG_USER}
#    password: ${PG_PASSWORD}

  #### H2 Config ####
#  datasource:
#    url: jdbc:h2:mem:expensedb;DB_CLOSE_DELAY=-1 # URL for H2 Db in memory mode
#    #    url: jdbc:h2:~/testdb # persisted database
#    driver-class-name: org.h2.Driver # H2 specific JDBC driver
#    platform: h2
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update # automatically updates or creates the database schema based on entity classes
#      show-sql: true # enables logging of SQL queries generated by JPA
#      database-platform: org.hibernate.dialect.H2Dialect